version: '3'
services: 
    https-portal:
        image: steveltn/https-portal:latest
        ports:
          - 80:80
          - 443:443
        restart: always
        environment:
          DOMAINS: 'jiokar.net -> http://nginx:8080'
          STAGE: production
        volumes:
          - ./https-portal:/var/lib/https-portal
    nginx:
        build: ./nginx
        ports: 
            - "8080:8080"
        volumes: 
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf